name: ai
channels:
  - conda-forge
dependencies:
  - python=3.11
  - pypdf
  - langchain
  - langchain-community
  - chromadb # Vector storage
  - pandas
  - pytest
  - boto3
  - ipykernel
  - unstructured
  - pip
  - pip:
    - "unstructured[md]"
